# These are supported funding model platforms

github: Mbilse# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Mbilse# Replace with a single Patreon username
open_collective:Mbilse # Replace with a single Open Collective username
ko_fi: Mbilse# Replace with a single Ko-fi username
tidelift: Mbilse # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: mbilse.github.io # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: Mbilse # Replace with a single Liberapay username
issuehunt: Mbilse# Replace with a single IssueHunt username
lfx_crowdfunding: Mbilse# Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: Mbilse# Replace with a single Polar username
buy_me_a_coffee: Mbilse# Replace with a single Buy Me a Coffee username
thanks_dev: Mbilse# Replace with a single thanks.dev username
custom: Mbilse# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
